In [2]:
#1.: reading images, displaying those and the RGB tensors of those
%pylab 
import imageio #!!!code has to be run in order to display the images!!!  every picture will be displayed in a different window
import matplotlib.pyplot as plt #the pics folder has to be put in the current working directory 

pics=[]  # the data of each picture will be stored in this list
images=[] # the name of each picture will be stored in here
for i in range(5):
    exec("""images.append('pic%d')"""%(i+1))
index=0
for image in images:
    plt.figure()   #new figure has to be opened before reading a new image 
    exec("""pics.append(imageio.imread('./pics/%s.jpg'))"""%image) # RGB channels are contained by an imageio.core.util.Image object,               
    print('Channels of the %d. image:'%(index+1))                         
    print(pics[index])
    plt.imshow(pics[index]) # displaying the image
    index+=1


Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib
Channels of the 1. image:
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
Channels of the 2. image:
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255

In [3]:
#2.: calculating the mean and deviation for every color of every pixel
import numpy as np
import math
import itertools
# the calculation of average and deviation should be made for each and every pixel and each different color
# using the five images, because in case of pattern recognition every color component of every pixel is a different feature
pixel_lists=[list(range(128)), list(range(128))]
pixels=itertools.product(*pixel_lists)  # this will result in an iterable object, which corresponds to the direct product of the two lists containing indices
means=np.zeros((128,128,3)) #preallocation of the matrices containing the mean values and deviations
devs=np.zeros((128,128,3))

for pixel in pixels: #iterating through the pixels
    for color in range(3): # iterating through the channels (R, G, B)
        aux_list=[] # auxiliary list, which corresponds to a given pixel and a given color and contains the intensity values for all the five pics
        for i in range(5):# iterating through the images
            aux_list.append(pics[i][pixel+(color,)])
        means[pixel+(color,)]=np.mean(aux_list)
        devs[pixel+(color,)]=math.sqrt(np.var(aux_list))
print('The average values:')
print(means)
print('The deviations:')
print(devs)



The average values:
[[[206.4 228.6 210.2]
  [207.6 228.4 210.2]
  [207.6 227.6 210.2]
  ...
  [207.8 227.8 209.8]
  [207.8 228.8 210.2]
  [207.4 228.6 209. ]]

 [[206.8 228.6 210.2]
  [207.  228.6 210.2]
  [207.2 228.4 210.2]
  ...
  [207.2 228.8 211.6]
  [207.  228.8 211. ]
  [207.6 228.6 210. ]]

 [[207.  228.6 210.2]
  [206.4 228.6 210.2]
  [206.  228.6 210.2]
  ...
  [206.8 228.8 211.4]
  [207.  228.  211. ]
  [208.2 228.2 210.2]]

 ...

 [[208.2 228.2 210.2]
  [207.  228.  211. ]
  [206.8 228.8 211.4]
  ...
  [207.4 228.2 209. ]
  [207.6 228.  208.8]
  [207.6 228.2 208.4]]

 [[207.6 228.6 210. ]
  [207.  228.8 211. ]
  [207.6 228.6 211.6]
  ...
  [207.6 228.  209. ]
  [207.6 228.  208.2]
  [208.  228.  208.2]]

 [[207.4 228.6 209. ]
  [207.8 228.8 210.2]
  [207.8 227.8 209.8]
  ...
  [207.6 228.  208.8]
  [208.  228.  208.2]
  [208.  228.  207.4]]]
The deviations:
[[[82.21338091 41.44683341 77.70559825]
  [82.86760525 41.32118101 77.70559825]
  [82.86760525 40.85388598 77.70559825

In [4]:
#2.: standardising the data
pics_std=[] # standardised data will be stored here, the tensors corresponding to each pic will be assigned to the list elements
for i in range(5):
    pics[i]=np.array(pics[i])
    std=(pics[i]-means)/devs
    pics_std.append(std)
print('The standardised data:')
print(pics_std)
print('========================================================')
means_std=np.zeros((128,128,3))
devs_std=np.zeros((128,128,3))

pixel_lists2=[list(range(128)), list(range(128))]
pixels2=itertools.product(*pixel_lists2)
# checking the mean values and deviations
for pix in pixels2: #iterating through the pixels
    for col in range(3): # iterating through the channels (R, G, B)
        aux_list=[]
        for i in range(5):# iterating through the images
            aux_list.append(pics_std[i][pix+(col,)])
        means_std[pix+(col,)]=np.mean(aux_list)
        devs_std[pix+(col,)]=math.sqrt(np.var(aux_list))
print('The average values after standardisation:')
print(means_std)
print('The deviations after standardisation:')
print(devs_std)

The standardised data:
[array([[[0.59114465, 0.6369606 , 0.57653504],
        [0.57199674, 0.64373765, 0.57653504],
        [0.57199674, 0.67068283, 0.57653504],
        ...,
        [0.57232685, 0.63249657, 0.57580038],
        [0.57232685, 0.63812156, 0.57653504],
        [0.5716696 , 0.6369606 , 0.57437212]],

       [[0.58477923, 0.6369606 , 0.57653504],
        [0.58158965, 0.6369606 , 0.57653504],
        [0.57839586, 0.64373765, 0.57653504],
        ...,
        [0.57134539, 0.63812156, 0.57922092],
        [0.57102408, 0.63812156, 0.57804737],
        [0.57199674, 0.6369606 , 0.57616596]],

       [[0.58158965, 0.6369606 , 0.57653504],
        [0.59114465, 0.6369606 , 0.57653504],
        [0.59748989, 0.6369606 , 0.57653504],
        ...,
        [0.57070561, 0.63812156, 0.57882589],
        [0.57102408, 0.63358639, 0.57804737],
        [0.57299612, 0.63469342, 0.57653504]],

       ...,

       [[0.57299612, 0.63469342, 0.57653504],
        [0.57102408, 0.63358639, 0.57804737]

The average values after standardisation:
[[[-8.88178420e-17  1.33226763e-16  1.33226763e-16]
  [ 1.33226763e-16 -1.77635684e-16  1.33226763e-16]
  [ 1.33226763e-16  1.33226763e-16  1.33226763e-16]
  ...
  [-8.88178420e-17 -2.66453526e-16 -1.33226763e-16]
  [-8.88178420e-17 -2.22044605e-16  1.33226763e-16]
  [-1.33226763e-16  1.33226763e-16 -4.44089210e-17]]

 [[-8.88178420e-17  1.33226763e-16  1.33226763e-16]
  [-4.44089210e-17  1.33226763e-16  1.33226763e-16]
  [ 1.33226763e-16 -1.77635684e-16  1.33226763e-16]
  ...
  [ 8.88178420e-17 -2.22044605e-16  8.88178420e-17]
  [ 0.00000000e+00 -2.22044605e-16  0.00000000e+00]
  [ 1.33226763e-16  1.33226763e-16 -4.44089210e-17]]

 [[-4.44089210e-17  1.33226763e-16  1.33226763e-16]
  [-8.88178420e-17  1.33226763e-16  1.33226763e-16]
  [-4.44089210e-17  1.33226763e-16  1.33226763e-16]
  ...
  [-1.33226763e-16 -2.22044605e-16 -8.88178420e-17]
  [ 0.00000000e+00 -4.44089210e-17  0.00000000e+00]
  [ 8.88178420e-17  3.10862447e-16  1.33226763e-16]]

In [5]:
# 3.: retrieving text from html webpage
import urllib
from bs4 import BeautifulSoup

url = "https://blog.keras.io/the-future-of-deep-learning.html"
html = urllib.request.urlopen(url).read() # this will read the html code as a bytearray
soup = BeautifulSoup(html, 'html.parser') # beatifulsoup object has to be created in order to be able to process the html code

text = soup.find_all(text=True) # finding all the contents which correspond to text property

output = ''
blacklist = [   # these tags are unwanted for us
    '[document]',
    'noscript',
    'header',
    'html',
    'meta',
    'head', 
    'input',
    'script',
    '!--[if IE]'
    '!--[if lte IE 7]'
]

for t in text:
    if t.parent.name not in blacklist: # filtering the unwanted parentnames
        output += '{} '.format(t)

print(output)


The future of deep learning 
 [if IE]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif] 
 [if lte IE 7]>
                <link rel="stylesheet" type="text/css" media="all" href="//blog.keras.io/css/ie.css"/>
                <script src="//blog.keras.io/js/IE8.js" type="text/javascript"></script><![endif] 
 [if lt IE 7]>
                <link rel="stylesheet" type="text/css" media="all" href="//blog.keras.io/css/ie6.css"/><![endif] 
 
 
 The Keras Blog  
 
 Keras  is a Deep Learning library for Python, that is simple, modular, and extensible.
                 
 Archives 
 
 Github 
 
 
 Documentation 
 
 
 Google Group 
 
  /#banner  
 
 
 The future of deep learning 
 
 
 
                Tue 18 July 2017
         
 
                By  Francois Chollet 
 
 In  Essays .  
 This post is adapted from Section 3 of Chapter 9 of my book,  Deep Learning with Python  (Manning Publications).  It is part of a series of two posts on the current 

In [6]:
#3. histogram 
%pylab
import pandas as pd
import matplotlib.pyplot as plt



char_list = list(output) # convert input to list of chars
to_remove=['.', ',', '"', '/', '(', ')', ':', '-', """'""", '=', '<', '>', '[', ']', ';', '!', '#', '?', '@', 
            '0', '1', '2', '3', '5', '6', '7', '8', '9', '_'] # these caracters 
for c in output:
    if c in to_remove:
        char_list.remove(c)
# create a dataframe where each char is one row
df = pd.DataFrame({'chars': char_list})
# drop all the space characters
df = df[df.chars != ' ']
# add a column for aggregation later
df['num'] = 1
# group rows by character type, count the occurences in each group

df = df.groupby('chars').sum()
plt.bar(df.index, df.num, width=0.5, color='g')
plt.title('Numbers of incidence of letters')
plt.show()

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


C:\anaconda\lib\site-packages\IPython\core\magics\pylab.py:160: UserWarning: pylab import has clobbered these variables: ['std', 'text']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"
